######################################################################
# Automatically generated by qmake (3.1) Thu Aug 20 19:36:43 2020
######################################################################

TEMPLATE = subdirs

# Directories

SUBDIRS += \
    fm-app-1
